import requests
import hashlib
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.exceptions import InvalidSignature

BASE_URL = "https://logistics-iot-edge.onrender.com"
DEVICE_ID = "device-001"
PUBLIC_KEY_PATH = "device_public.pem"   # generated by the upload script


def get_latest_manifest():
    r = requests.get(f"{BASE_URL}/devices/{DEVICE_ID}/check-update")
    return r.json()


def verify(firmware_bytes, expected_hash, signature_hex, public_key_path):
    computed_hash = hashlib.sha256(firmware_bytes).hexdigest()
    if computed_hash != expected_hash:
        print("[CRITICAL] Hash mismatch — firmware corrupted or tampered. Dropping payload.")
        return False

    public_key = serialization.load_pem_public_key(open(public_key_path, "rb").read())
    try:
        public_key.verify(
            bytes.fromhex(signature_hex),
            firmware_bytes,
            ec.ECDSA(hashes.SHA256())   # ECDSA, not RSA padding — matches the key type
        )
    except InvalidSignature:
        print("[CRITICAL] Signature invalid. Dropping payload.")
        return False

    print("[OK] Verification passed.")
    return True


data = get_latest_manifest()
real_firmware = requests.get(f"{BASE_URL}{data['download_url']}").content

print("=== TEST 0: Real firmware, real key (should PASS) ===")
verify(real_firmware, data["sha256_hash"], data["signature_hex"], PUBLIC_KEY_PATH)

print("\n=== TEST 1: Tampered firmware (should FAIL on hash) ===")
tampered = bytearray(real_firmware)
tampered[0] = tampered[0] ^ 0xFF
verify(bytes(tampered), data["sha256_hash"], data["signature_hex"], PUBLIC_KEY_PATH)

print("\n=== TEST 2: Wrong public key (should FAIL on signature) ===")
wrong_priv = ec.generate_private_key(ec.SECP256R1())
with open("wrong_public.pem", "wb") as f:
    f.write(wrong_priv.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo))
verify(real_firmware, data["sha256_hash"], data["signature_hex"], "wrong_public.pem")

print("\nAll negative tests completed.")